export const businessCatalog = {
  'Mercado do Sol': { sector:'Mercado', open:7, close:21, products:{alimentos:{price:28,stock:420,target:500},higiene:{price:17,stock:180,target:220}} },
  'Café do Largo': { sector:'Cafeteria', open:7, close:23, products:{café:{price:9,stock:160,target:180},refeição:{price:24,stock:90,target:110}} },
  'Farmácia Popular': { sector:'Farmácia', open:8, close:22, products:{remédio:{price:32,stock:140,target:170},higiene:{price:14,stock:100,target:130}} },
  'Hotel Central': { sector:'Hotelaria', open:0, close:24, products:{diária:{price:145,stock:22,target:22}} },
  'Hospital São Lucas': { sector:'Saúde', open:0, close:24, products:{consulta:{price:80,stock:80,target:100}} },
  'Escola Municipal': { sector:'Educação', open:7, close:18, products:{} },
  'Faculdade Municipal': { sector:'Educação', open:7, close:23, products:{} },
  'Delegacia': { sector:'Serviço público', open:0, close:24, products:{} },
  'Prefeitura': { sector:'Serviço público', open:8, close:17, products:{} },
  'UBS Vila Esperança': { sector:'Atenção básica', open:7, close:19, products:{consulta:{price:0,stock:120,target:120}} },
  'CAPS Bem Viver': { sector:'Saúde mental', open:8, close:20, products:{terapia:{price:0,stock:80,target:80}} },
  'Restaurante Sabor da Vila': { sector:'Restaurante', open:11, close:23, products:{refeição:{price:34,stock:140,target:180}} },
  'Livraria Horizonte': { sector:'Livraria', open:9, close:20, products:{livro:{price:46,stock:120,target:150}} },
  'Cinema Municipal': { sector:'Entretenimento', open:14, close:24, products:{ingresso:{price:24,stock:180,target:220}} },
  'Academia Movimento': { sector:'Bem-estar', open:6, close:23, products:{mensalidade:{price:85,stock:100,target:120}} },
  'Funerária Serenidade': { sector:'Serviços funerários', open:0, close:24, products:{básico:{price:2800,stock:12,target:12},tradicional:{price:4700,stock:8,target:8},cerimonial:{price:6900,stock:5,target:5}} }
  ,'Instituto Médico-Legal': { sector:'Medicina legal', open:0, close:24, products:{} }
  ,'Padaria Aurora': {sector:'Padaria',open:5,close:20,minimumStaff:3,requiredRoles:['Padeiro','Atendente','Caixa'],interactions:['tomar café','comprar pão','lanchar'],products:{pão:{price:8,stock:180,target:240},lanche:{price:16,stock:80,target:110}}}
  ,'Bar Esquina 12': {sector:'Bar',open:16,close:2,minimumStaff:3,nightlife:true,adultOnly:true,requiredRoles:['Bartender','Garçom','Segurança'],interactions:['beber com amigos','assistir jogo','conhecer pessoas'],products:{bebida:{price:18,stock:160,target:220},petisco:{price:26,stock:80,target:120}}}
  ,'Pub Ferro & Fogo': {sector:'Pub',open:18,close:3,minimumStaff:4,nightlife:true,adultOnly:true,requiredRoles:['Bartender','Cozinheiro','Garçom','Músico'],interactions:['ouvir música ao vivo','jantar','encontrar colegas'],products:{bebida:{price:24,stock:150,target:210},refeição:{price:38,stock:70,target:100}}}
  ,'Clube Eclipse': {sector:'Clube social',open:19,close:4,minimumStaff:5,nightlife:true,adultOnly:true,requiredRoles:['DJ','Bartender','Segurança','Promotor de eventos'],interactions:['dançar','participar de festa','flertar'],products:{ingresso:{price:35,stock:220,target:260},bebida:{price:22,stock:190,target:250}}}
  ,'Boate Nebulosa': {sector:'Boate',open:22,close:6,minimumStaff:5,nightlife:true,adultOnly:true,requiredRoles:['DJ','Bartender','Segurança','Atendente'],interactions:['dançar até tarde','celebrar','conhecer pessoas'],products:{ingresso:{price:42,stock:180,target:220},bebida:{price:25,stock:170,target:230}}}
  ,'Casa de Shows Estação': {sector:'Casa de shows',open:18,close:2,minimumStaff:6,nightlife:true,requiredRoles:['Músico','Técnico de som','Bilheteiro','Segurança'],interactions:['assistir show','encontrar fãs','celebrar em grupo'],products:{ingresso:{price:48,stock:260,target:300},bebida:{price:16,stock:180,target:230}}}
  ,'Casa Rubi': {sector:'Entretenimento adulto',open:20,close:5,minimumStaff:4,nightlife:true,adultOnly:true,requiredRoles:['Recepcionista','Segurança','Artista adulta'],interactions:['buscar companhia adulta','beber','socializar em ambiente adulto'],regulated:true,products:{entrada:{price:55,stock:100,target:120},bebida:{price:28,stock:90,target:130}}}
  ,'Oficina Central': {sector:'Serviços automotivos',open:7,close:19,minimumStaff:3,requiredRoles:['Mecânico','Eletricista automotivo','Atendente'],interactions:['revisar veículo','reparar avaria'],products:{reparo:{price:240,stock:35,target:45},peça:{price:110,stock:70,target:100}}}
  ,'Posto Avenida': {sector:'Posto de combustível',open:0,close:24,minimumStaff:3,requiredRoles:['Frentista','Caixa','Gerente'],interactions:['abastecer','comprar conveniência'],products:{combustível:{price:120,stock:900,target:1200},conveniência:{price:15,stock:150,target:210}}}
  ,'Banco Cooperativo': {sector:'Serviços financeiros',open:9,close:16,minimumStaff:4,requiredRoles:['Caixa bancário','Analista de crédito','Gerente'],interactions:['pagar contas','pedir empréstimo','investir'],products:{serviço:{price:12,stock:200,target:200}}}
  ,'Ferro-Velho Oeste': {sector:'Reciclagem automotiva',open:8,close:18,minimumStaff:2,requiredRoles:['Sucateiro','Mecânico'],interactions:['vender sucata','comprar peça usada'],illegalActivity:'desmanche clandestino',frontBusiness:true,products:{sucata:{price:75,stock:80,target:120},peça:{price:95,stock:65,target:90}}}
  ,'Porão 77': {sector:'Bar privado',open:20,close:5,minimumStaff:3,nightlife:true,adultOnly:true,frontBusiness:true,illegalActivity:'cassino clandestino',requiredRoles:['Crupiê clandestino','Cobrador','Segurança clandestino'],interactions:['participar de jogo privado','fazer aposta ilegal'],products:{entrada:{price:40,stock:70,target:90},aposta:{price:120,stock:120,target:150}}}
  ,'Depósito Norte': {sector:'Armazém logístico',open:6,close:18,minimumStaff:3,frontBusiness:true,illegalActivity:'contrabando',requiredRoles:['Contrabandista','Olheiro','Transportador clandestino'],interactions:['negociar carga sem nota'],products:{eletrônico:{price:420,stock:45,target:70},mercadoria:{price:160,stock:80,target:110}}}
  ,'Agência Prisma': {sector:'Consultoria financeira',open:9,close:18,minimumStaff:3,frontBusiness:true,illegalActivity:'lavagem de dinheiro',requiredRoles:['Operador financeiro ilegal','Laranja','Contador clandestino'],interactions:['movimentar recursos de fachada'],products:{consultoria:{price:280,stock:90,target:110},serviço:{price:150,stock:100,target:120}}}
  ,'Casa Vênus': {sector:'Casa noturna adulta',open:20,close:5,minimumStaff:4,nightlife:true,adultOnly:true,frontBusiness:true,illegalActivity:'serviços adultos sem licença',requiredRoles:['Profissional do sexo','Recepcionista','Segurança clandestino','Agenciador ilegal'],interactions:['buscar companhia adulta','participar de evento privado'],products:{entrada:{price:65,stock:80,target:100},companhia:{price:240,stock:45,target:60}}}
  ,'Banca do Viaduto': {sector:'Comércio informal',open:10,close:23,minimumStaff:2,frontBusiness:true,illegalActivity:'receptação',requiredRoles:['Receptador','Falsificador'],interactions:['comprar item sem procedência'],products:{peça:{price:85,stock:70,target:90},eletrônico:{price:260,stock:55,target:75}}}
  ,'Imobiliária Horizonte': {sector:'Serviços imobiliários',open:8,close:18,minimumStaff:4,requiredRoles:['Corretor de imóveis','Avaliador imobiliário','Administrador de locações','Assistente jurídico'],interactions:['visitar imóvel','assinar contrato','avaliar propriedade','negociar aluguel'],products:{avaliação:{price:320,stock:60,target:60},administração:{price:180,stock:100,target:100}}}
  ,'Concessionária Avenida': {sector:'Comércio automotivo',open:8,close:19,minimumStaff:5,requiredRoles:['Vendedor de veículos','Consultor financeiro','Mecânico de inspeção','Despachante','Gerente comercial'],interactions:['testar veículo','negociar compra','simular financiamento','vender usado'],products:{veículo:{price:48000,stock:22,target:28},inspeção:{price:240,stock:70,target:70}}}
  ,'Central Táxi Vila': {sector:'Transporte individual',open:0,close:24,minimumStaff:6,requiredRoles:['Taxista','Taxista','Operador de rádio','Despachante de corridas','Mecânico de frota','Gerente de mobilidade'],interactions:['solicitar táxi','agendar corrida','despachar motorista'],products:{corrida:{price:28,stock:200,target:200},agendamento:{price:8,stock:100,target:100}}}
  ,'Construtora Horizonte': {sector:'Construção civil',open:7,close:18,minimumStaff:6,requiredRoles:['Engenheiro civil','Arquiteto','Mestre de obras','Pedreiro','Eletricista predial','Corretor de lançamentos'],interactions:['avaliar terreno','planejar obra','negociar apartamento'],products:{projeto:{price:2800,stock:24,target:24},reforma:{price:8500,stock:12,target:12}}}
  ,'Cartório Civil': {sector:'Serviços registrais',open:8,close:17,minimumStaff:4,requiredRoles:['Tabelião','Escrevente','Oficial de registro','Atendente'],interactions:['registrar escritura','reconhecer documento','formalizar união'],products:{registro:{price:185,stock:140,target:140},escritura:{price:920,stock:55,target:55}}}
  ,'Clínica Veterinária Vida Animal': {sector:'Saúde animal',open:7,close:22,minimumStaff:4,requiredRoles:['Médico veterinário','Auxiliar veterinário','Recepcionista','Tosador'],interactions:['consultar animal','vacinar animal','comprar cuidado pet'],products:{consulta:{price:130,stock:65,target:65},vacina:{price:86,stock:80,target:100}}}
  ,'Laboratório Vida': {sector:'Diagnóstico',open:6,close:19,minimumStaff:5,requiredRoles:['Biomédico','Técnico de laboratório','Flebotomista','Recepcionista','Auxiliar administrativo'],interactions:['coletar exame','retirar resultado'],products:{exame:{price:74,stock:130,target:150},checkup:{price:240,stock:45,target:60}}}
  ,'Centro Odontológico Sorriso': {sector:'Saúde bucal',open:8,close:20,minimumStaff:4,requiredRoles:['Dentista','Auxiliar de saúde bucal','Recepcionista','Técnico em prótese'],interactions:['realizar consulta odontológica','fazer tratamento'],products:{consulta:{price:110,stock:80,target:90},tratamento:{price:360,stock:35,target:45}}}
  ,'Salão Bela Vila': {sector:'Beleza',open:9,close:21,minimumStaff:4,requiredRoles:['Cabeleireiro','Manicure','Esteticista','Recepcionista'],interactions:['cortar cabelo','fazer tratamento estético','conversar no salão'],products:{corte:{price:58,stock:90,target:90},cosmético:{price:42,stock:70,target:100}}}
  ,'Barbearia Central': {sector:'Barbearia',open:8,close:20,minimumStaff:3,requiredRoles:['Barbeiro','Barbeiro','Atendente'],interactions:['cortar cabelo','aparar barba','conversar na barbearia'],products:{corte:{price:45,stock:90,target:90},produto:{price:32,stock:55,target:75}}}
  ,'Pet Shop Amigo': {sector:'Pet shop',open:8,close:20,minimumStaff:4,requiredRoles:['Gerente de pet shop','Vendedor','Tosador','Entregador'],interactions:['comprar ração','agendar banho e tosa'],products:{ração:{price:68,stock:100,target:150},higiene:{price:38,stock:80,target:110}}}
  ,'Loja Estação Moda': {sector:'Vestuário',open:9,close:21,minimumStaff:4,requiredRoles:['Gerente de loja','Vendedor','Caixa','Estoquista'],interactions:['experimentar roupa','comprar vestuário'],products:{roupa:{price:95,stock:160,target:220},calçado:{price:130,stock:90,target:130}}}
  ,'Pizzaria Forno Alto': {sector:'Pizzaria',open:17,close:1,minimumStaff:5,requiredRoles:['Pizzaiolo','Cozinheiro','Garçom','Entregador','Caixa'],interactions:['jantar com amigos','pedir pizza','comemorar'],products:{refeição:{price:48,stock:120,target:160},bebida:{price:11,stock:130,target:180}}}
  ,'Sorveteria Primavera': {sector:'Sorveteria',open:10,close:23,minimumStaff:3,requiredRoles:['Sorveteiro','Atendente','Caixa'],interactions:['tomar sorvete','encontrar amigos'],products:{sobremesa:{price:16,stock:130,target:170},café:{price:8,stock:70,target:90}}}
  ,'Agência Municipal de Emprego': {sector:'Serviço de emprego',open:8,close:17,minimumStaff:5,requiredRoles:['Agente de emprego','Orientador profissional','Assistente social','Analista de dados','Recepcionista'],interactions:['procurar vaga','participar de entrevista','fazer curso profissional'],products:{orientação:{price:0,stock:150,target:150},curso:{price:0,stock:80,target:80}}}
  ,'Centro de Convivência do Idoso': {sector:'Assistência social',open:7,close:19,minimumStaff:5,requiredRoles:['Assistente social','Cuidador de idosos','Terapeuta ocupacional','Educador físico','Cozinheiro'],interactions:['participar de oficina','fazer atividade leve','encontrar amigos'],products:{oficina:{price:0,stock:100,target:100},refeição:{price:0,stock:90,target:110}}}
  ,'Museu da Cidade': {sector:'Cultura',open:9,close:18,minimumStaff:5,requiredRoles:['Museólogo','Mediador cultural','Historiador','Bilheteiro','Segurança'],interactions:['visitar exposição','participar de visita guiada'],products:{ingresso:{price:12,stock:180,target:200},livro:{price:38,stock:60,target:80}}}
};

export const shiftTemplates = [
  {name:'Comercial',start:8,end:17,days:[0,1,2,3,4],hours:40},
  {name:'Manhã',start:6,end:14,days:[0,1,2,3,4,5],hours:36},
  {name:'Tarde',start:14,end:22,days:[0,1,2,3,4,5],hours:36},
  {name:'Noturno',start:22,end:6,days:[0,1,2,3],hours:32},
  {name:'Parcial',start:9,end:13,days:[1,2,3,4,5],hours:20},
  {name:'Escala 12×36',start:7,end:19,days:[0,2,4,6],hours:36}
];

export function isWorking(person, day, hour){
  if(!person.shift || !person.shift.days.includes(day)) return false;
  return person.shift.end < person.shift.start ? hour>=person.shift.start||hour<person.shift.end : hour>=person.shift.start&&hour<person.shift.end;
}
